variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "vpc_cidr" {}
variable "vpcname" {}
variable "envname" {}
variable "Ownername" {}
variable "public_subnet1_cidr" {}
variable "public_subnet1_AZ" {}
variable "public_subnet1_name" {}
variable "public_subnet2_cidr" {}
variable "public_subnet2_AZ" {}
variable "public_subnet2_name" {}
variable "public_subnet3_cidr" {}
variable "public_subnet3_AZ" {}
variable "public_subnet3_name" {}
variable "myvpc_IGW" {}